options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'DOCKER_BUILDKIT=1'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    env:
      - 'DOCKER_BUILDKIT=1'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/moodyfoodz/moodyfoodz/backend:$COMMIT_SHA', '.']

images:
  - 'us-central1-docker.pkg.dev/moodyfoodz/moodyfoodz/backend:$COMMIT_SHA'